"""Run layer: orchestrate a single analysis report end-to-end.

fetch (data) → assemble (context) → optional chart → generate (llm) → publish.
This is importable so an analysis can be produced programmatically; the
``generate_analysis.py`` CLI is a thin wrapper over :func:`run_analysis`.
"""

from __future__ import annotations

from pathlib import Path

from .config import ANALYSIS_TYPES, TODAY
from .config.providers import resolve_chain
from .context import build_context
from .data.charts import generate_plotly_candlestick_chart
from .data.sources import fetch_data
from .llm import call_llm, run_with_fallback
from .publish import GENERATED_BY as _GENERATED_BY, dedup_path, frontmatter
from .utils.mermaid import sanitize_mermaid_blocks


def build_technical_chart_embed(data: dict, ticker: str, output_dir) -> str:
    """Return the Markdown/HTML chart embed for technical reports ('' if none)."""
    if data.get("hist") is None:
        return ""
    print("  Generating interactive candlestick chart with MA30/60/200 …")
    chart_result = generate_plotly_candlestick_chart(data["hist"], ticker, str(output_dir))
    if not (isinstance(chart_result, dict) and chart_result.get("plotly_html")):
        return ""
    png_filename = chart_result.get("png_filename", "")
    plotly_html = chart_result.get("plotly_html", "")
    if png_filename:
        # Markdown image (not a raw <img>) so MkDocs rewrites the relative path
        # for its directory URLs; `markdown="1"` lets md_in_html parse it inside
        # the <details>, and the blank lines make GitHub do the same.
        return (
            f'<details markdown="1">\n'
            f'<summary>📊 靜態圖表 (點擊展開)</summary>\n'
            f'\n'
            f'![Technical Chart]({png_filename})\n'
            f'\n'
            f'</details>\n'
            f'\n'
            f'{plotly_html}\n\n'
        )
    return plotly_html + "\n\n"


def save_analysis_report(ticker: str, content: str, output_dir: Path,
                         analysis_type: str, provider: str = "claude",
                         model: str = "") -> Path:
    """Save report with YAML frontmatter and same-day deduplication."""
    output_dir = Path(output_dir)
    meta = ANALYSIS_TYPES[analysis_type]
    prefix = meta["filename_prefix"]
    label = meta["label"]
    ext = meta.get("ext", ".md")

    base = f"{prefix}_{TODAY}_{provider}"  # provider: "openai" | "claude" | "gemini"
    path = dedup_path(output_dir, base, ext)

    if ext == ".html":
        path.write_text(content, encoding="utf-8")
    else:
        # Repair LLM-emitted Mermaid syntax (unquoted parens/colons in node
        # labels, etc.) so the source .md GitHub renders directly is valid,
        # not only the docs-site copy. Only ```mermaid fences are touched, so
        # any embedded chart HTML is left byte-for-byte intact. Idempotent, so
        # build_docs re-running it later is a no-op.
        content = sanitize_mermaid_blocks(content)
        generated_by = _GENERATED_BY.get(provider, "Claude AI")
        fm = frontmatter({
            "title": f'"{ticker} {label} {TODAY}"',
            "date": TODAY,
            "ticker": ticker,
            "analysis_type": analysis_type,
            "provider": provider,
            "model": model,
            "language": "zh-TW",
            "generated_by": f"{generated_by} (scripts/generate_analysis.py)",
        })
        path.write_text(fm + content, encoding="utf-8")

    print(f"  ✅ saved → {path}")
    return path


def run_analysis(ticker: str, analysis_type: str, provider: str | None,
                 model: str | None, max_tokens: int, output_dir: Path) -> Path:
    """Fetch data, build context, generate the report, and save it. Returns path.

    ``provider`` / ``model`` are the primary override (either may be ``None``);
    the report is generated by trying the resolved provider fallback chain and
    keeping the first success — so the data/context are fetched only once and
    reused across fallback attempts. The provider that actually produced the
    report is recorded in the saved frontmatter.
    """
    output_dir = Path(output_dir)
    attempts = resolve_chain(provider, model)

    print("[1/3] Fetching financial data from Yahoo Finance …")
    data = fetch_data(ticker)
    context = build_context(data, analysis_type)

    chart_embed = ""
    if analysis_type == "technical-analysis":
        chart_embed = build_technical_chart_embed(data, ticker, output_dir)

    print(f"[2/3] Generating report (chain: {' → '.join(p for p, _ in attempts)}) …")
    report, used_provider, used_model = run_with_fallback(
        attempts,
        lambda p, m: call_llm(ticker, context, analysis_type, p, m, max_tokens),
    )

    print(f"[3/3] Saving report (generated by {used_provider}) …")
    return save_analysis_report(ticker, chart_embed + report, output_dir,
                                analysis_type, provider=used_provider, model=used_model)


__all__ = ["run_analysis", "save_analysis_report", "build_technical_chart_embed"]
